CREATE DATABASE BD_SistemTec


CREATE TABLE TBESTADO (
  IDESTADO INTEGER IDENTITY ,
  NMESTADO VARCHAR(40)  NOT NULL  ,
  NMSIGLA VARCHAR(2)  NOT NULL  ,
PRIMARY KEY(IDESTADO));
GO

CREATE TABLE TBCIDADE (
  IDCIDADE INTEGER IDENTITY ,
  IDESTADO INTEGER  FOREIGN KEY (IDESTADO) REFERENCES TBESTADO (IDESTADO),
  NMCIDADE VARCHAR(40)  NOT NULL  ,
PRIMARY KEY(IDCIDADE));
GO

CREATE TABLE TBBAIRRO (
  IDBAIRRO INTEGER IDENTITY ,
  IDCIDADE INTEGER  FOREIGN KEY (IDCIDADE) REFERENCES TBCIDADE (IDCIDADE),
  NMBAIRRO VARCHAR(40)  NOT NULL  ,
PRIMARY KEY(IDBAIRRO));
GO

CREATE TABLE TBENDERECO (
  IDENDERECO INTEGER IDENTITY ,
  IDBAIRRO INTEGER  FOREIGN KEY (IDBAIRRO) REFERENCES TBBAIRRO (IDBAIRRO),
  NRNUMERO INTEGER  NOT NULL ,
  NMRUA VARCHAR(40)  NOT NULL  ,
  NMCOMPLEMENTO VARCHAR(100)  NOT NULL  ,
PRIMARY KEY(IDENDERECO));
GO

---------------------------------------------------------------------------------

CREATE TABLE TBTECNICO (
  IDTECNICO INTEGER IDENTITY ,
  IDENDERECO INTEGER  FOREIGN KEY (IDENDERECO) REFERENCES TBENDERECO (IDENDERECO),
  NRCPF INTEGER NOT NULL   ,
  NMNOME VARCHAR(100)  NOT NULL  ,
  NMSENHA VARCHAR(40)  NOT NULL  ,
  NMUSUARIO VARCHAR(40)  NOT NULL  ,
PRIMARY KEY(IDTECNICO));
GO

CREATE TABLE TBCLIENTE (
  IDCLIENTE INTEGER IDENTITY ,
  IDENDERECO INTEGER  FOREIGN KEY (IDENDERECO) REFERENCES TBENDERECO (IDENDERECO),
  NRCPFCNPJ INTEGER NOT NULL   ,
  NMNOME VARCHAR(100)  NOT NULL  ,
  NMNOMERAZAO VARCHAR(100)  NOT NULL  ,
  NRTELEFONE INTEGER NOT NULL   ,
  NMEMAIL VARCHAR(100)  NOT NULL  ,
PRIMARY KEY(IDCLIENTE));
GO

CREATE TABLE TBFORNECEDOR (
  IDFORNECEDOR INTEGER IDENTITY ,
  IDENDERECO INTEGER  FOREIGN KEY (IDENDERECO) REFERENCES TBENDERECO (IDENDERECO),
  NRCNPJ INTEGER NOT NULL   ,
  NMNOME VARCHAR(100)  NOT NULL  ,
  NMNOMERAZAO VARCHAR(100)  NOT NULL  ,
  NRTELEFONE INTEGER NOT NULL   ,
  NMEMAIL VARCHAR(100)  NOT NULL  ,
PRIMARY KEY(IDFORNECEDOR));
GO

---------------------------------------------------------------------------------

CREATE TABLE TBTIPOPRODUTO (
  IDTIPOPRODUTO INTEGER IDENTITY ,
  NMDESCRICAO VARCHAR(40)  NOT NULL  ,
PRIMARY KEY(IDTIPOPRODUTO));
GO

CREATE TABLE TBPRODUTO (
  IDPRODUTO INTEGER IDENTITY ,
  IDTIPOPRODUTO INTEGER  FOREIGN KEY (IDTIPOPRODUTO) REFERENCES TBTIPOPRODUTO (IDTIPOPRODUTO),
  IDFORNECEDOR INTEGER  FOREIGN KEY (IDFORNECEDOR) REFERENCES TBFORNECEDOR (IDFORNECEDOR),
  DCQUANTIDADE INT NOT NULL  ,
  DCVALORUNITARIO DECIMAL(8,2)  NOT NULL  ,
  NMDESCRICAO VARCHAR(100)  NOT NULL  ,
PRIMARY KEY(IDPRODUTO));
GO

CREATE TABLE TBTIPOEQUIPAMENTO (
  IDTIPOEQUIPAMENTO INTEGER IDENTITY ,
  NMDESCRICAO VARCHAR(40)  NOT NULL  ,
PRIMARY KEY(IDTIPOEQUIPAMENTO));
GO

CREATE TABLE TBEQUIPAMENTO (
  IDEQUIPAMENTO INTEGER IDENTITY ,
  IDCLIENTE INTEGER  FOREIGN KEY (IDCLIENTE) REFERENCES TBCLIENTE (IDCLIENTE),
  IDTIPOEQUIPAMENTO INTEGER  FOREIGN KEY (IDTIPOEQUIPAMENTO) REFERENCES TBTIPOEQUIPAMENTO (IDTIPOEQUIPAMENTO),
  NMDESCRICAO VARCHAR(100)  NOT NULL  ,
PRIMARY KEY(IDEQUIPAMENTO));
GO

---------------------------------------------------------------------------------

CREATE TABLE TBORDEMSERVICO (
  IDORDEMSERVICO INTEGER IDENTITY ,
  IDEQUIPAMENTO INTEGER  FOREIGN KEY (IDEQUIPAMENTO) REFERENCES TBEQUIPAMENTO (IDEQUIPAMENTO),
  IDTECNICO INTEGER  FOREIGN KEY (IDTECNICO) REFERENCES TBTECNICO (IDTECNICO),
  DTENTRADA DATETIME ,
  DTSERVICO DATETIME  ,
  DTSAIDA DATETIME ,
  NMDESCRICAO VARCHAR(100) ,
  DCMAODEOBRA DECIMAL(8,2)  ,
  DCVALORTOTAL DECIMAL(8,2)  ,
PRIMARY KEY(IDORDEMSERVICO));
GO

CREATE TABLE TBPRODUTOSERVICO (
  IDPRODUTOSERVICO INTEGER IDENTITY ,
  IDPRODUTO INTEGER  FOREIGN KEY (IDPRODUTO) REFERENCES TBPRODUTO (IDPRODUTO),
  IDORDEMSERVICO INTEGER  FOREIGN KEY (IDORDEMSERVICO) REFERENCES TBORDEMSERVICO (IDORDEMSERVICO),
PRIMARY KEY(IDPRODUTOSERVICO));
GO
